elastic_user: "{{ vault_elastic_user }}"
elastic_password: "{{ vault_elastic_password }}"
kibana_system_password: "{{ vault_kibana_system_password }}"
sigma_user: "{{ vault_sigma_user }}"
sigma_password: "{{ vault_sigma_password }}"
kibana_url: "http://10.10.10.30:5601"
elasticsearch_url: "http://10.10.10.30:9200"
sigma_cli_path: "/opt/sigma-pipeline/.venv/bin/sigma"

encrypted_saved_objects_key: "{{ vault_encrypted_saved_objects_key }}"
encryption_key: "{{ vault_encryption_key }}"

caldera_group: linux_siem

internal_interface: eth2
internal_ip: 192.168.70.10
internal_gateway: 192.168.70.1
