- name: Ensure DNS points to Domain Controller
  ansible.windows.win_dns_client:
    adapter_names: "Ethernet 3" 
    ipv4_addresses:
      - "{{ domain_controller_ip }}"

- name: Flush DNS cache to ensure new settings are applied
  ansible.windows.win_command: ipconfig /flushdns



- name: Reboot after rename
  ansible.windows.win_reboot:
  
- name: Join machine to domain
  ansible.windows.win_domain_membership:
    dns_domain_name: "{{ domain_name }}"
    domain_admin_user: "{{ domain_admin_user }}"
    domain_admin_password: "{{ domain_admin_password }}"
    domain_ou_path: "{{ domain_ou_path | default(omit) }}"
    state: domain
  register: domain_join_result
  # Вот это "магия", которая лечит твою ошибку:
  become: yes
  become_method: runas
  become_user: System

- name: Reboot after domain join
  ansible.windows.win_reboot:
    msg: "Rebooting after domain join"
    pre_reboot_delay: 5
  when:
    - reboot_after_join | default(true)
    - domain_join_result.reboot_required